image:
  repository: python-api
  tag: latest
  pullPolicy: Never

ingress:
  host: localhost

redis:
  password: redis-123

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 80



